language: generic
dist: xenial
os: linux
services:
    - docker

before_install:
    - docker build -t dltgamon/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dltgamon/docker-react npm run test